"""The health facility points, packed for the Places overlay.

The care facilities in health_facilities_pk (in_care_layer): hospitals,
primary care, mother-and-child, clinics, traditional medicine, laboratories
and TB and leprosy centres - not pharmacies, vets, opticians, ambulances or
the morgue, which stay in the table. Packed as build_overlay_schools.py packs
the schools: four decimal places, delta-encoded in latitude order, with the
sector and care group in one small integer (sector * 10 + group).

Usage:
  build_overlay_health.py --src <health_facilities_pk parquet> --out <js>
"""
import argparse, gzip, json, pathlib

import duckdb

GROUPS = ['Hospital', 'Primary care', 'Mother and child', 'Clinic',
          'Traditional medicine', 'Laboratory and diagnostics', 'TB and leprosy']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    con = duckdb.connect()
    case = ' '.join(f"WHEN '{g}' THEN {i}" for i, g in enumerate(GROUPS))
    rows = con.sql(f"""
        SELECT round(lat, 4), round(lng, 4),
               CASE sector WHEN 'Government' THEN 1 ELSE 0 END,
               CASE care_group {case} END
        FROM '{a.src}'
        WHERE in_care_layer AND lat BETWEEN 23 AND 38 AND lng BETWEEN 60 AND 78
        ORDER BY 1, 2""").fetchall()
    lat, lng, flag, plat, plng = [], [], [], 0, 0
    for r in rows:
        la, ln = int(round(r[0] * 1e4)), int(round(r[1] * 1e4))
        lat.append(la - plat); lng.append(ln - plng)
        plat, plng = la, ln
        flag.append(r[2] * 10 + r[3])
    payload = {'n': len(rows), 'lat': lat, 'lng': lng, 'f': flag, 'group': GROUPS,
               'sector': ['Private', 'Government']}
    out = pathlib.Path(a.out)
    out.write_text(
        '/* Data Darbar - health facility points for the Places overlay (ALHASAN\n'
        '   Systems, 2017, CC0). Coordinates delta-encoded in ten-thousandths of a\n'
        '   degree, latitude order. Generated by etl/places/build_overlay_health.py. */\n'
        'window.DD_HEALTH_POINTS=' + json.dumps(payload, separators=(',', ':')) + ';\n')
    gov = sum(1 for r in rows if r[2])
    print(f'  {len(rows):,} points -> {out}  ({out.stat().st_size/1e6:.2f} MB, '
          f'{len(gzip.compress(out.read_bytes()))/1e6:.2f} MB gzipped)')
    print(f'    {gov:,} government, {len(rows) - gov:,} private')


if __name__ == '__main__':
    main()
