"""The school points, packed small enough to draw over any choropleth.

121,020 of the 125,317 schools in the layer carry coordinates. 82,294 of those
are a fix on the school itself; the rest sit on the centroid of a settlement,
tehsil, markaz or cluster because that is as close as the source gets. The map
draws the two differently - a solid dot against a hollow ring - because a point
placed at a tehsil centroid is a claim about a tehsil, not about a building,
and a map that draws both the same way overstates what is known.

Packing. Coordinates go to four decimal places, which is about 11 metres and
finer than any of these positions are, then are delta-encoded against the
previous point in latitude order: neighbouring schools differ in the fourth
decimal, so the deltas are one or two digits where the absolutes are seven.
Level, gender and whether the fix is real pack into one small integer.

Usage:
  build_overlay_schools.py --src <schools parquet> --out <js>
"""
import argparse, gzip, json, pathlib

import duckdb

LEVEL = ['primary', 'middle', 'high', 'other']
GENDER = ['Boys', 'Girls', 'Unknown']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    con = duckdb.connect()
    con.execute('SET threads TO 1')
    rows = con.sql(f"""
        SELECT round(lat, 4) AS lat, round(lng, 4) AS lng,
               CASE level_std WHEN 'primary' THEN 0 WHEN 'middle' THEN 1
                              WHEN 'high' THEN 2 ELSE 3 END AS lv,
               CASE gender WHEN 'Boys' THEN 0 WHEN 'Girls' THEN 1 ELSE 2 END AS gd,
               CASE WHEN coord_precision = 'school' THEN 1 ELSE 0 END AS fix,
               district_key_boundary AS dk
        FROM '{a.src}'
        WHERE has_coords AND lat IS NOT NULL AND lng IS NOT NULL
          AND lat BETWEEN 23 AND 38 AND lng BETWEEN 60 AND 78
        ORDER BY lat, lng""").fetchall()

    lat, lng, flag = [], [], []
    plat = plng = 0
    for r in rows:
        la, ln = int(round(r[0] * 1e4)), int(round(r[1] * 1e4))
        lat.append(la - plat)
        lng.append(ln - plng)
        plat, plng = la, ln
        flag.append(r[4] * 100 + r[2] * 10 + r[3])

    payload = {'n': len(rows), 'lat': lat, 'lng': lng, 'f': flag,
               'level': LEVEL, 'gender': GENDER}
    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, separators=(',', ':'))
    out.write_text(
        '/* Data Darbar - school points for the Places overlay. Coordinates are\n'
        '   delta-encoded in ten-thousandths of a degree, latitude order.\n'
        '   Generated by etl/places/build_overlay_schools.py; do not edit. */\n'
        'window.DD_SCHOOL_POINTS=' + body + ';\n')

    size = out.stat().st_size
    gz = len(gzip.compress(out.read_bytes()))
    fixed = sum(1 for r in rows if r[4])
    print(f'  {len(rows):,} points -> {out}')
    print(f'    {size/1e6:.2f} MB raw, {gz/1e6:.2f} MB gzipped')
    print(f'    {fixed:,} located on the school, '
          f'{len(rows) - fixed:,} on a centroid')
    print(con.sql(f"""SELECT level_std, count(*) AS n FROM '{a.src}'
        WHERE has_coords GROUP BY 1 ORDER BY 2 DESC""").df().to_string(index=False))


if __name__ == '__main__':
    main()
