"""The Places payload: the picker's index, and the values small enough to ship.

Phase 0 measured the alternative. DuckDB-WASM is 6,295 KB over the wire, against
the 1,826 KB of JavaScript it would replace, so putting the engine in front of
first paint costs more than it saves. The warehouse stays the single source of
truth and the build emits a payload from it - the same relationship
census_series_index already has to the census panels.

What ships and what does not is decided by size, not by source:

  the index      every indicator Places can offer, 5,801 of them. Interned and
                 columnar it is about 1.4 MB raw and 50 KB gzipped, so the
                 picker can search everything with no engine at all.

  curated values one file per indicator group, fetched when something in that
                 group is first chosen. 70 groups, 1,560 values on average, the
                 largest 15,336. Shipping all 109,235 up front to show one
                 indicator would cost more than the file it replaces; a group
                 costs about 35 KB.

  census values  17 MB across two panels. They stay on Parquet and are read by
                 range request when a series is chosen, which is how the census
                 map already works.

  crop values    78,425 rows over three measures. Same treatment - the index
                 lists them, the values are read on demand.

Interning matters more than it looks. The index's labels are built from a small
vocabulary - 740 indicator stems, 284 column headings, four localities, five
sexes - so storing the parts and rebuilding the label in the browser costs a
third of storing the labels themselves.

Usage:
  build_payload.py --warehouse <dir> --out-dir <app/data>
"""
import argparse, json, pathlib, re

HERE_PLACES = pathlib.Path(__file__).resolve().parent

import duckdb


def safe(name):
    """A group key as a file name: the keys are already tame, but not trusted."""
    return re.sub(r'[^A-Za-z0-9_-]', '_', name)


def js_name(name):
    return re.sub(r'[^A-Za-z0-9_]', '_', name)


def intern(values):
    """[v0, v1, ...], [index per row] - the vocabulary and the pointers."""
    seen, vocab, idx = {}, [], []
    for v in values:
        if v not in seen:
            seen[v] = len(vocab)
            vocab.append(v)
        idx.append(seen[v])
    return {'v': vocab, 'i': idx}


def columnar(rows, names, interned):
    cols = list(zip(*rows)) if rows else [[] for _ in names]
    return {n: (intern(list(c)) if n in interned else list(c))
            for n, c in zip(names, cols)}


def write(path, global_name, obj, what):
    body = json.dumps(obj, separators=(',', ':'), ensure_ascii=False)
    path.write_text(
        f'/* Data Darbar - {what}. Generated by etl/places/build_payload.py;\n'
        f'   do not edit by hand. */\n'
        f'window.{global_name}={body};\n')
    return path.stat().st_size


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warehouse', required=True)
    ap.add_argument('--out-dir', required=True)
    a = ap.parse_args()

    import sys
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    from topics import ORDER

    con = duckdb.connect()
    con.execute('SET threads TO 1')
    W = pathlib.Path(a.warehouse)
    out = pathlib.Path(a.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    # ── the index ───────────────────────────────────────────────────────────
    order_vals = ', '.join("('" + t + "', " + str(i) + ")" for i, t in enumerate(ORDER))
    ix = con.sql(f"""
        SELECT level, topic, topic_label, group_key, group_label, dataset,
               indicator, label, measure, metric, coalesce(dp, -1) AS dp, source,
               coalesce(families, '') AS families,
               coalesce(years, []) AS years,
               coalesce(localities, ['all']) AS localities,
               coalesce(sexes, ['all']) AS sexes,
               shapes, units, min_value, max_value,
               CASE WHEN redundant THEN 1 ELSE 0 END AS redundant
        FROM '{(W / 'place_indicator_index.parquet').as_posix()}' ix
        LEFT JOIN (VALUES {order_vals}) AS o(t, ord) ON o.t = ix.topic
        -- the picker lists topics in the order the design gives, not
        -- alphabetically by their key
        ORDER BY o.ord, group_key, label, level""").fetchall()
    names = ('level topic topic_label group_key group_label dataset indicator label '
             'measure metric dp source families years localities sexes shapes units '
             'min_value max_value redundant').split()
    # the list columns intern as a whole: a locality set repeats across thousands
    # of indicators, so the distinct combinations are a handful
    rows = [tuple('\u001f'.join(x) if isinstance(x, list) else x for x in r) for r in ix]

    # ── PBS's typing, corrected for display only ───────────────────────────
    # AFGHANI for Afghan, BANGALI for Bengali, KOHIOSTANI, Intermidiate,
    # REALATIONSHIP, HOUSE HOLD. The rule and its limits live in labels.py;
    # what matters here is WHERE it is applied. Only the three columns a
    # reader sees are changed. The indicator key, the catalogue table and the
    # raw_indicator/raw_col columns beside them keep PBS's own spelling, so
    # the series is still findable by what was printed and the audit trail is
    # unbroken.
    sys.path.insert(0, str(HERE_PLACES))
    from labels import fix_words
    at = {n: names.index(n) for n in ('label', 'measure', 'metric')}
    fixed = 0
    def _fix(r):
        nonlocal fixed
        r = list(r)
        for j in at.values():
            if r[j]:
                v = fix_words(r[j])
                if v != r[j]:
                    r[j] = v
                    fixed += 1
        return tuple(r)
    rows = [_fix(r) for r in rows]
    print(f'  {fixed} display labels corrected for PBS spelling slips')

    # ── the navigation hierarchy ───────────────────────────────────────────
    # Topic / subtopic / family / metric form, joined on the compound source
    # key. The original topic column stays exactly as it was: it keys the map
    # colour scales (DDMapScales.for) and disambiguates census table numbers
    # that PBS reused between the two censuses, neither of which is a
    # navigation question. This adds a way to find a series; it does not
    # rename one.
    HK = ('level', 'group_key', 'indicator')
    hier = json.loads((HERE_PLACES / 'hierarchy.json').read_text())
    hmap, hv = hier['map'], hier['vocab']
    at = {n: names.index(n) for n in HK}
    keys = ['\u001f'.join(str(r[at[n]]) for n in HK) for r in rows]
    # The 463 source totals and column headings are in the catalogue but not
    # in the subject tree: the hierarchy proposal describes the 5,201 series a
    # reader browses, and a table's own total is not one of them. They are
    # reachable by search and carry no topic.
    red = names.index('redundant')
    browsable = [i for i, r in enumerate(rows) if not r[red]]

    # Both directions, loudly. A row with no destination would otherwise fall
    # into whichever bucket sorted first and be findable only by knowing its
    # name; a destination with no row means the hierarchy is describing an
    # index that no longer exists. Either way the fix is to regenerate the
    # crosswalk, not to paper over it here.
    missing = [keys[i] for i in browsable if keys[i] not in hmap]
    stale = set(hmap) - {keys[i] for i in browsable}
    assert not missing, (
        f'{len(missing)} index rows have no place in the hierarchy, e.g. '
        f'{missing[0]!r}')
    assert not stale, (
        f'{len(stale)} hierarchy entries match no index row, e.g. '
        f'{sorted(stale)[0]!r}')
    assert len(set(keys)) == len(keys), 'the compound source key is not unique'

    unresolved = set(hier['unresolved_review'])
    for n in ('h_topic', 'h_sub', 'h_family', 'h_metric', 'h_controls'):
        names.append(n)
    # h_review: the label could not be resolved to a definition.
    # h_sum:    the values may be added across places (a count, not a mean).
    # h_norm:   the values may be read against the population (a count OF
    #           PEOPLE). Both are decided in build_hierarchy.py from the
    #           crosswalk's metric form, which types the quantity rather than
    #           guessing at its wording.
    # h_note: what this percentage is a percentage OF, where the source's own
    #         denominator needs saying. Empty for everything else.
    names += ['h_review', 'h_sum', 'h_norm', 'h_note']
    # A source total sits outside the subject tree and so has no metric form,
    # but it is still almost always a count - it is the total OF counts - and
    # leaving h_sum at 0 made the strip announce "a rate cannot be totalled"
    # over a headcount. For census rows dp carries the panel's own is_rate
    # flag, which is the signal the tree itself used before the crosswalk
    # existed, so it is what these fall back to. They stay out of the per-head
    # conversions, which need a numerator universe nobody has assigned them.
    dp_at, src_at = names.index('dp'), names.index('source')
    def blank_for(r):
        is_rate = r[src_at] == 'census' and r[dp_at] is not None and r[dp_at] > 0
        return ('', '', '', '', '', 0, 0 if is_rate else 1, 0, '')
    rows = [r + (tuple(hv[k][hmap[keys[i]][j]] for j, k in enumerate(
                     ('topic', 'sub', 'family', 'metric', 'controls')))
                 + (1 if hmap[keys[i]][5] in unresolved else 0,
                    hmap[keys[i]][6], hmap[keys[i]][7],
                    hv['note'][hmap[keys[i]][8]])
                 if keys[i] in hmap else blank_for(r))
            for i, r in enumerate(rows)]

    P = columnar(rows, names,
                 {'level', 'topic', 'topic_label', 'group_key', 'group_label',
                  'dataset', 'source', 'families', 'years', 'localities',
                  'sexes', 'label', 'indicator', 'measure', 'metric',
                  'h_topic', 'h_sub', 'h_family', 'h_metric', 'h_controls',
                  'h_note'})
    # The rows stay in the order the old topic list wants, because that list
    # is still drawn from them. The hierarchy's own order - general subjects
    # first, so Places does not open on Agriculture - travels beside them
    # rather than being inferred from whichever topic happens to appear first.
    P['h_topic_order'] = hv['topic']
    n1 = write(out / 'places_index.js', 'DD_PLACES_IX', P,
               f'Places picker index, {len(ix):,} indicators')

    # ── provenance, in one file ────────────────────────────────────────────
    # low_n and n_obs are filed under the survey family while the figures they
    # qualify are filed under the app's group, so they cannot travel in the
    # group's own file. 8,019 rows is small enough to ship once.
    prov = con.sql(f"""
        SELECT v.level, v.map_key, v.group_key, v.indicator,
               round(v.value, 4) AS value
        FROM '{(W / 'place_indicators.parquet').as_posix()}' v
        WHERE v.value IS NOT NULL AND NOT EXISTS (
          SELECT 1 FROM '{(W / 'place_indicator_index.parquet').as_posix()}' i
          WHERE i.group_key = v.group_key AND i.indicator = v.indicator)
        ORDER BY group_key, indicator, map_key""").fetchall()
    PV = columnar(prov, 'level map_key group_key indicator value'.split(),
                  {'level', 'map_key', 'group_key', 'indicator'})
    np = write(out / 'places' / 'provenance.js', 'DD_PLACES_PROV', PV,
               f'Places provenance flags, {len(prov):,} rows')
    print(f'  places/provenance.js {len(prov):>6,} flags      {np/1e6:5.2f} MB')

    # ── the curated values, one file per group ─────────────────────────────
    vdir = out / 'places'
    vdir.mkdir(parents=True, exist_ok=True)
    for stale in vdir.glob('*.js'):
        if stale.name not in ('overlay_schools.js', 'provenance.js'):
            stale.unlink()

    groups = [r[0] for r in con.sql(f"""
        SELECT DISTINCT group_key FROM '{(W / 'place_indicators.parquet').as_posix()}'
        WHERE value IS NOT NULL ORDER BY 1""").fetchall()]
    total_vals, total_bytes, biggest = 0, 0, ('', 0)
    for gk in groups:
        vals = con.sql(f"""
            SELECT level, map_key, indicator, coalesce(year, '') AS year,
                   round(value, 4) AS value, coalesce(relation, 'exact') AS relation,
                   coalesce(note, '') AS note
            FROM '{(W / 'place_indicators.parquet').as_posix()}'
            WHERE value IS NOT NULL AND group_key = ?
            ORDER BY indicator, year, map_key""", params=[gk]).fetchall()
        V = columnar(vals,
                     'level map_key indicator year value relation note'.split(),
                     {'level', 'map_key', 'indicator', 'year', 'relation', 'note'})
        # the file names itself, so a group can be fetched without a manifest
        n = write(vdir / f'{safe(gk)}.js', 'DD_PLACES_G_' + js_name(gk),
                  {'g': gk, 'd': V}, f'Places values for {gk}, {len(vals):,} figures')
        total_vals += len(vals)
        total_bytes += n
        if n > biggest[1]:
            biggest = (gk, n)

    import gzip
    gz = len(gzip.compress((out / 'places_index.js').read_bytes()))
    print(f'  places_index.js  {len(ix):>6,} indicators  {n1/1e6:5.2f} MB raw, '
          f'{gz/1e6:.3f} MB gzipped   [eager]')
    print(f'  places/*.js      {total_vals:>6,} values in {len(groups)} groups, '
          f'{total_bytes/1e6:5.2f} MB total   [on demand]')
    print(f'    average {total_bytes/len(groups)/1e3:.0f} KB, '
          f'largest {biggest[0]} at {biggest[1]/1e3:.0f} KB')


if __name__ == '__main__':
    main()
