"""The Places payload: the picker's index, and the values small enough to ship.

Phase 0 measured the alternative. DuckDB-WASM is 6,295 KB over the wire, against
the 1,826 KB of JavaScript it would replace, so putting the engine in front of
first paint costs more than it saves. The warehouse stays the single source of
truth and the build emits a payload from it - the same relationship
census_series_index already has to the census panels.

What ships and what does not is decided by size, not by source:

  the index      every indicator Places can offer, 5,801 of them. Interned and
                 columnar it is about 1.4 MB raw and 50 KB gzipped, so the
                 picker can search everything with no engine at all.

  curated values one file per indicator group, fetched when something in that
                 group is first chosen. 70 groups, 1,560 values on average, the
                 largest 15,336. Shipping all 109,235 up front to show one
                 indicator would cost more than the file it replaces; a group
                 costs about 35 KB.

  census values  17 MB across two panels. They stay on Parquet and are read by
                 range request when a series is chosen, which is how the census
                 map already works.

  crop values    78,425 rows over three measures. Same treatment - the index
                 lists them, the values are read on demand.

Interning matters more than it looks. The index's labels are built from a small
vocabulary - 740 indicator stems, 284 column headings, four localities, five
sexes - so storing the parts and rebuilding the label in the browser costs a
third of storing the labels themselves.

Usage:
  build_payload.py --warehouse <dir> --out-dir <app/data>
"""
import argparse, json, pathlib, re

import duckdb


def safe(name):
    """A group key as a file name: the keys are already tame, but not trusted."""
    return re.sub(r'[^A-Za-z0-9_-]', '_', name)


def js_name(name):
    return re.sub(r'[^A-Za-z0-9_]', '_', name)


def intern(values):
    """[v0, v1, ...], [index per row] - the vocabulary and the pointers."""
    seen, vocab, idx = {}, [], []
    for v in values:
        if v not in seen:
            seen[v] = len(vocab)
            vocab.append(v)
        idx.append(seen[v])
    return {'v': vocab, 'i': idx}


def columnar(rows, names, interned):
    cols = list(zip(*rows)) if rows else [[] for _ in names]
    return {n: (intern(list(c)) if n in interned else list(c))
            for n, c in zip(names, cols)}


def write(path, global_name, obj, what):
    body = json.dumps(obj, separators=(',', ':'), ensure_ascii=False)
    path.write_text(
        f'/* Data Darbar - {what}. Generated by etl/places/build_payload.py;\n'
        f'   do not edit by hand. */\n'
        f'window.{global_name}={body};\n')
    return path.stat().st_size


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warehouse', required=True)
    ap.add_argument('--out-dir', required=True)
    a = ap.parse_args()

    import sys
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    from topics import ORDER

    con = duckdb.connect()
    con.execute('SET threads TO 1')
    W = pathlib.Path(a.warehouse)
    out = pathlib.Path(a.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    # ── the index ───────────────────────────────────────────────────────────
    order_vals = ', '.join("('" + t + "', " + str(i) + ")" for i, t in enumerate(ORDER))
    ix = con.sql(f"""
        SELECT level, topic, topic_label, group_key, group_label, dataset,
               indicator, label, coalesce(dp, -1) AS dp, source,
               coalesce(years, []) AS years,
               coalesce(localities, ['all']) AS localities,
               coalesce(sexes, ['all']) AS sexes,
               shapes, units, min_value, max_value
        FROM '{(W / 'place_indicator_index.parquet').as_posix()}' ix
        LEFT JOIN (VALUES {order_vals}) AS o(t, ord) ON o.t = ix.topic
        -- the picker lists topics in the order the design gives, not
        -- alphabetically by their key
        ORDER BY o.ord, group_key, label, level""").fetchall()
    names = ('level topic topic_label group_key group_label dataset indicator label '
             'dp source years localities sexes shapes units min_value max_value').split()
    # the list columns intern as a whole: a locality set repeats across thousands
    # of indicators, so the distinct combinations are a handful
    rows = [tuple('\u001f'.join(x) if isinstance(x, list) else x for x in r) for r in ix]
    P = columnar(rows, names,
                 {'level', 'topic', 'topic_label', 'group_key', 'group_label',
                  'dataset', 'source', 'years', 'localities', 'sexes', 'label',
                  'indicator'})
    n1 = write(out / 'places_index.js', 'DD_PLACES_IX', P,
               f'Places picker index, {len(ix):,} indicators')

    # ── the curated values, one file per group ─────────────────────────────
    vdir = out / 'places'
    vdir.mkdir(parents=True, exist_ok=True)
    for stale in vdir.glob('*.js'):
        stale.unlink()

    groups = [r[0] for r in con.sql(f"""
        SELECT DISTINCT group_key FROM '{(W / 'place_indicators.parquet').as_posix()}'
        WHERE value IS NOT NULL ORDER BY 1""").fetchall()]
    total_vals, total_bytes, biggest = 0, 0, ('', 0)
    for gk in groups:
        vals = con.sql(f"""
            SELECT level, map_key, indicator, coalesce(year, '') AS year,
                   round(value, 4) AS value, coalesce(relation, 'exact') AS relation,
                   coalesce(note, '') AS note
            FROM '{(W / 'place_indicators.parquet').as_posix()}'
            WHERE value IS NOT NULL AND group_key = ?
            ORDER BY indicator, year, map_key""", params=[gk]).fetchall()
        V = columnar(vals,
                     'level map_key indicator year value relation note'.split(),
                     {'level', 'map_key', 'indicator', 'year', 'relation', 'note'})
        # the file names itself, so a group can be fetched without a manifest
        n = write(vdir / f'{safe(gk)}.js', 'DD_PLACES_G_' + js_name(gk),
                  {'g': gk, 'd': V}, f'Places values for {gk}, {len(vals):,} figures')
        total_vals += len(vals)
        total_bytes += n
        if n > biggest[1]:
            biggest = (gk, n)

    import gzip
    gz = len(gzip.compress((out / 'places_index.js').read_bytes()))
    print(f'  places_index.js  {len(ix):>6,} indicators  {n1/1e6:5.2f} MB raw, '
          f'{gz/1e6:.3f} MB gzipped   [eager]')
    print(f'  places/*.js      {total_vals:>6,} values in {len(groups)} groups, '
          f'{total_bytes/1e6:5.2f} MB total   [on demand]')
    print(f'    average {total_bytes/len(groups)/1e3:.0f} KB, '
          f'largest {biggest[0]} at {biggest[1]/1e3:.0f} KB')


if __name__ == '__main__':
    main()
