"""The curated tehsil vocabulary: which indicators exist, and what they are called.

Lifted from app.js's INDICATOR_GROUPS, which is where these labels have lived
and drifted. The direction of travel is the other way round - the app should
read its vocabulary from the warehouse index rather than carry its own - so
this is the ETL taking ownership of it, not a second copy of it.

Each group names the table its values come from and the key that table uses.
The keys differ by source, which is most of why this file is needed: the school
and health layers carry dd_id, the satellite layers call the same identifier
tehsil_id, and the Mouza Census has codes of its own that reach PBS through
etl/mouza2020/mouza2020_tehsil_crosswalk_pbs.csv. Mouza values are not columns
at all - they are derived, and the derivation stays in
etl/mouza2020/build_payload.py, which this imports rather than restates.
"""

GROUPS = {
    'rwi': {
        'label': 'Relative Wealth — Meta RWI',
        'dataset': 'Meta Relative Wealth Index · ~2.4 km grid',
        'topic': 'poverty',
        'table': 'tehsil_satellite',
        'key': 'tehsil_id',
        'dp': {'rwi': 2, 'rwi_pct': 0},
        'indicators': {
            'rwi': 'Relative Wealth Index',
            'rwi_pct': 'Relative Wealth (percentile)',
        },
    },
    'satPop': {
        'label': 'Population — WorldPop 2020',
        'dataset': 'WorldPop 2020 (UN-adjusted) · 1 km',
        'topic': 'poverty',
        'table': 'tehsil_satellite',
        'key': 'tehsil_id',
        'dp': {'popdens': 0, 'pop': 0},
        'indicators': {
            'popdens': 'Population Density (per km²)',
            'pop': 'Population',
        },
    },
    'nightlights': {
        'label': 'Night-time Lights — VIIRS 2020–2026',
        'dataset': 'VIIRS DNB · June composites 2020–2026',
        'topic': 'poverty',
        'table': 'tehsil_nightlights',
        'key': 'tehsil_id',
        'dp': {'density': 2},
        'indicators': {
            'density': 'Lights per km² (radiance)',
            'growth': 'Growth in Lights 2020→2026 (%)',
        },
    },
    'schoolAccess': {
        'label': 'Distance to School — Girls’ and Boys’ Government Schools',
        'dataset': 'Adaad school layer 2026-09 · WorldPop 2020 · 1 km',
        'topic': 'education',
        'table': 'school_access_tehsil',
        'key': 'dd_id',
        'dp': {'girls_middle_km': 1, 'boys_middle_km': 1, 'gap_middle_km': 1, 'girls_high_km': 1, 'boys_high_km': 1, 'gap_high_km': 1, 'girls_primary_km': 1, 'boys_primary_km': 1, 'gap_primary_km': 1, 'girls_middle_over5km_pct': 0, 'boys_middle_over5km_pct': 0, 'girls_middle_schools': 0, 'boys_middle_schools': 0, 'girls_share_middle_pct': 0},
        'indicators': {
            'girls_middle_km': 'Nearest girls’ middle school (km)',
            'boys_middle_km': 'Nearest boys’ middle school (km)',
            'gap_middle_km': 'Girls’ minus boys’ distance, middle (km)',
            'girls_middle_over5km_pct': 'Population over 5 km from a girls’ middle school (%)',
            'boys_middle_over5km_pct': 'Population over 5 km from a boys’ middle school (%)',
            'girls_high_km': 'Nearest girls’ high school (km)',
            'boys_high_km': 'Nearest boys’ high school (km)',
            'gap_high_km': 'Girls’ minus boys’ distance, high (km)',
            'girls_primary_km': 'Nearest girls’ school, any level (km)',
            'boys_primary_km': 'Nearest boys’ school, any level (km)',
            'gap_primary_km': 'Girls’ minus boys’ distance, any level (km)',
            'girls_middle_schools': 'Girls’ middle-or-above schools',
            'boys_middle_schools': 'Boys’ middle-or-above schools',
            'girls_share_middle_pct': 'Girls’ share of middle-or-above schools (%)',
        },
    },
    'healthAccess': {
        'label': 'Travel Time to Care — by Tehsil',
        'dataset': 'Malaria Atlas accessibility surfaces · WorldPop 2020 · 1 km',
        'topic': 'health',
        'table': 'health_access_tehsil',
        'key': 'dd_id',
        'dp': {'mot_popw_mean': 0, 'wal_popw_mean': 0, 'mot_mean': 0, 'wal_mean': 0, 'mot_pct_pop_gt60': 0, 'wal_pct_pop_gt60': 0, 'mot_pct_pop_gt30': 0, 'mot_pct_pop_gt120': 0, 'wal_pct_pop_gt120': 0},
        'indicators': {
            'mot_popw_mean': 'Travel time to care, motorised (min)',
            'wal_popw_mean': 'Travel time to care, walking (min)',
            'mot_pct_pop_gt60': 'Population over 60 min from care, motorised (%)',
            'wal_pct_pop_gt60': 'Population over 60 min from care, walking (%)',
            'mot_pct_pop_gt30': 'Population over 30 min, motorised (%)',
            'mot_pct_pop_gt120': 'Population over 2 hours, motorised (%)',
            'wal_pct_pop_gt120': 'Population over 2 hours, walking (%)',
            'mot_mean': 'Motorised, unweighted mean of cells (min)',
            'wal_mean': 'Walking, unweighted mean of cells (min)',
        },
    },
    'mouza_electricity_energy': {
        'label': 'Electricity & energy',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'elec_none': 'No electricity (%)',
            'elec_partial': 'Electricity in some houses only (%)',
            'elec_all': 'Electricity in all houses (%)',
            'solar': 'Solar in use (%)',
            'alt_none': 'No alternative energy source (%)',
        },
    },
    'mouza_drinking_water': {
        'label': 'Drinking water',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'w_piped': 'Government piped supply (%)',
            'w_pump': 'Hand or motor pump (%)',
            'w_well': 'Well (%)',
            'w_surface': 'River, canal or pond (%)',
            'w_karez': 'Spring, ravine or karez (%)',
            'w_treated': 'Filtration or RO plant (%)',
            'wdepth': 'Water table depth (feet)',
        },
    },
    'mouza_streets_roads': {
        'label': 'Streets & roads',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'st_dirt': 'Dirt streets (%)',
            'st_paved': 'Cemented or bricked streets (%)',
            'st_metaled': 'Metalled streets (%)',
            'road_metaled': 'On a metalled road (%)',
        },
    },
    'mouza_housing': {
        'label': 'Housing',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'h_bricked': 'Houses mainly brick (%)',
            'h_mud': 'Houses mainly mud (%)',
        },
    },
    'mouza_schools': {
        'label': 'Schools',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'sch_pri_f': "Girls' primary school (%)",
            'sch_pri_m': "Boys' primary school (%)",
            'sch_mid_f': "Girls' middle school (%)",
            'sch_mid_m': "Boys' middle school (%)",
            'sch_high_f': "Girls' high school (%)",
            'sch_high_m': "Boys' high school (%)",
            'col_f': "Girls' college (%)",
            'col_m': "Boys' college (%)",
            'madrasa': 'Deeni madrasa (%)',
        },
    },
    'mouza_health': {
        'label': 'Health',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'hf_bhu': 'Basic health unit (%)',
            'hf_rhc': 'Rural health centre (%)',
            'hf_hosp': 'Hospital or dispensary (%)',
            'hf_private': 'Private MBBS doctor (%)',
            'hf_midwife': 'Midwife (%)',
            'hf_mch': 'Mother and child centre (%)',
        },
    },
    'mouza_connectivity': {
        'label': 'Connectivity',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'mobile': 'Mobile signal (%)',
            'net_mobile': 'Mobile internet (%)',
            'net_dsl': 'Fixed-line DSL (%)',
            'transport': 'Public transport (%)',
            'post': 'Post office (%)',
            'police': 'Police station (%)',
        },
    },
    'mouza_cooking_fuel': {
        'label': 'Cooking fuel',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'fuel_wood': 'Firewood (%)',
            'fuel_dung': 'Animal dung cake (%)',
            'fuel_gas': 'Piped sui gas (%)',
            'fuel_lpg': 'LPG (%)',
        },
    },
    'mouza_markets_credit': {
        'label': 'Markets & credit',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'bazar': 'Bazar (%)',
            'mkt_grain': 'Grain wholesale market (%)',
            'bank_online': 'Commercial bank branch (%)',
            'credit_mfi': 'Microfinance lender (%)',
            'ind_none': 'No industry of any scale (%)',
        },
    },
    'mouza_hazards': {
        'label': 'Hazards',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'dis_any': 'Exposed to natural disaster (%)',
            'dis_flood': 'Flood (%)',
            'dis_drought': 'Drought (%)',
        },
    },
    'mouza_settlement': {
        'label': 'Settlement',
        'dataset': 'Mouza Census 2020',
        'topic': 'ruralFacilities',
        'table': 'mouza_tehsil',
        'key': 'mouza_tehsil_code',
        'dp': {},
        'indicators': {
            'rural': 'Mouzas classified rural (%)',
            'urbanish': 'Mouzas urban or partly urban (%)',
            'unpop': 'Mouzas unpopulated (%)',
        },
    },
}
