"""How much of Pakistan's trade the detailed tables actually account for.

trade_reconciliation compares the published monthly and annual trade totals
against what you get by adding up their own parts - every trading partner, and
every commodity group. It has been in the warehouse, unpublished, while
trade.html drew the partner and group charts without saying how complete they
are.

They are not always complete, and the shortfall is large and dated. Before
2011-12 the partner tables account for 85 to 91 per cent of imports: somewhere
between a tenth and a seventh of everything Pakistan bought in the 2000s is not
attributed to any country. From 2011-12 the gap closes to under 2 per cent and
mostly under 1. The commodity groups add to the total in every year.

That is the difference between a chart of Pakistan's trading partners and a
chart of the partners PBS managed to name, and a reader working on the Musharraf
years needs to know which one they are looking at. Hence a chart, not a
footnote.

Two quirks kept rather than smoothed:
  - the USD columns are zero before 2015-16, because PBS only began publishing
    the dollar series then. Zero here means not reported, so the rupee basis is
    the default and the dollar view starts where the data does.
  - 'FY_from_quarters' is not a period alongside the months and quarters; it is
    the fiscal-year row, assembled from them. It is kept as the annual series
    and never mixed into the monthly one.

Usage: build_recon_payload.py --warehouse <dir> --out <js>
"""
import argparse, json, pathlib

import duckdb


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warehouse', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    con = duckdb.connect()
    con.execute('SET threads TO 1')
    W = pathlib.Path(a.warehouse).as_posix()
    R = f"'{W}/trade_reconciliation.parquet'"
    rows = lambda sql: [list(r) for r in con.sql(sql).fetchall()]

    # Coverage as a percentage of the published total, which is the only form
    # in which the four series are comparable across two decades of inflation.
    def cover(basis):
        return rows(f"""
            SELECT fy,
              round(100.0 * countries_imports_{basis}
                    / nullif(totals_imports_{basis}, 0), 2) AS c_imp,
              round(100.0 * groups_imports_{basis}
                    / nullif(totals_imports_{basis}, 0), 2)  AS g_imp,
              round(100.0 * countries_exports_{basis}
                    / nullif(totals_exports_{basis}, 0), 2)  AS c_exp,
              round(100.0 * groups_exports_{basis}
                    / nullif(totals_exports_{basis}, 0), 2)  AS g_exp,
              months_in_totals
            FROM {R} WHERE period = 'FY_from_quarters'
            ORDER BY fy""")

    # And the rupees behind the percentage, so the gap can be read as money.
    gap = rows(f"""
        SELECT fy,
               round(totals_imports_pkr / 1e9, 1)                  AS imp_bn,
               round(countries_minus_totals_imports_pkr / 1e9, 1)  AS c_imp_gap,
               round(groups_minus_totals_imports_pkr / 1e9, 1)     AS g_imp_gap,
               round(totals_exports_pkr / 1e9, 1)                  AS exp_bn,
               round(countries_minus_totals_exports_pkr / 1e9, 1)  AS c_exp_gap,
               round(groups_minus_totals_exports_pkr / 1e9, 1)     AS g_exp_gap
        FROM {R} WHERE period = 'FY_from_quarters'
        ORDER BY fy""")

    payload = {
        'pkr': {'rows': cover('pkr'),
                'cols': ['fy', 'c_imp', 'g_imp', 'c_exp', 'g_exp', 'months']},
        'usd': {'rows': cover('usd'),
                'cols': ['fy', 'c_imp', 'g_imp', 'c_exp', 'g_exp', 'months']},
        'gap': {'rows': gap,
                'cols': ['fy', 'imp_bn', 'c_imp_gap', 'g_imp_gap',
                         'exp_bn', 'c_exp_gap', 'g_exp_gap']},
    }
    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        '/* Data Darbar - trade coverage payload. Generated by\n'
        '   etl/economy/build_recon_payload.py; do not edit by hand. */\n'
        'window.DD_RECON=' + json.dumps(payload, separators=(',', ':')) + ';\n')

    pkr = payload['pkr']['rows']
    early = [r for r in pkr if r[0] < '2011-12']
    late = [r for r in pkr if r[0] >= '2011-12']
    assert all(r[1] < 95 for r in early), 'the early import shortfall vanished'
    assert all(r[1] > 95 for r in late), 'a late year lost its partner coverage'
    for k in payload:
        print(f'  {k:<4} {len(payload[k]["rows"]):>3} rows')
    print(f'  partner coverage of imports: '
          f'{min(r[1] for r in early):.1f}-{max(r[1] for r in early):.1f}% to '
          f'{min(r[1] for r in late):.1f}-{max(r[1] for r in late):.1f}% '
          f'from 2011-12')
    print(f'  -> {out} ({out.stat().st_size/1e3:.1f} KB)')


if __name__ == '__main__':
    main()
