"""The price index the Economy and State pages deflate rupee series with.

GDP deflator by fiscal year: GDP at market prices in current rupees over the
same at constant 2015-16 prices (PBS national accounts), 2015-16 = 100.

PBS publishes two bases. From 1999-00 the 2015-16 base (Tables 4 and 5, and
the newer rows of Tables 2 and 3); before it, Tables 2 and 3 on the 1980-81
base, back to 1960-61. 1999-00 is printed on both, so the older series is
linked at that year: each earlier deflator is scaled by the ratio of the two
1999-00 deflators. This moves the level of the old series, never its
year-to-year change.

The GDP deflator, not the CPI, because the series it deflates - the budget,
public spending and revenue, national aggregates - are spent and raised
across the whole economy, not on a consumer's basket. Monthly series that
would need a monthly index are left nominal.

    python3 etl/economy/build_deflator.py --warehouse app/data/warehouse \
        --out app/data/deflator_data.js
"""
import argparse, json, pathlib

import duckdb


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warehouse', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    na = (pathlib.Path(a.warehouse) / 'national_accounts.parquet').as_posix()
    con = duckdb.connect()

    def gdp(sheet, item):
        return con.execute(f"""SELECT year, value FROM '{na}' WHERE table_sheet = ?
            AND item = ? AND value IS NOT NULL ORDER BY year, value""", [sheet, item]).fetchall()

    # 2015-16 base, 1999-00 onwards
    cur = dict(gdp('Table 4', 'G GDP at mp (GVA+T-S)'))
    con_ = dict(gdp('Table 5', 'G GDP at mp (GVA+T-S)'))
    new = {y: cur[y] / con_[y] * 100 for y in cur if y in con_ and con_[y]}
    # Tables 2 and 3: the 1980-81 base before 1999-00. In 1999-00 they print
    # both bases; the old one is the smaller current-price figure.
    c2, k3 = {}, {}
    for y, v in gdp('TABLE-2', 'GDP (MP)'):
        c2.setdefault(y, []).append(v)
    for y, v in gdp('TABLE-3', 'GDP (MP)'):
        k3.setdefault(y, []).append(v)
    old = {}
    for y in c2:
        if y in k3 and y <= '1999-00':
            old[y] = min(c2[y]) / min(k3[y]) * 100
    link = '1999-00'
    assert link in old and link in new, 'no overlap year to link the two bases'
    factor = new[link] / old[link]
    defl = {y: round(v * factor, 4) for y, v in old.items() if y < link}
    defl.update({y: round(v, 4) for y, v in new.items()})
    years = sorted(defl)
    # every year present, none missing in the middle
    starts = [int(y[:4]) for y in years]
    assert starts == list(range(starts[0], starts[-1] + 1)), 'a gap in the deflator'
    assert abs(defl['2015-16'] - 100) < 1e-6
    base = max(y for y in years if y < years[-1])        # latest complete year

    out = {
        'fy': defl,
        'base': '2015-16',
        'real_base': base,          # real series are shown in this year's rupees
        'linked': link,
        'source': 'PBS National Accounts: GDP at market prices, current over constant '
                  '2015-16 prices (Tables 4 and 5); before 1999-00, Tables 2 and 3 on the '
                  '1980-81 base, linked at 1999-00.',
    }
    dest = pathlib.Path(a.out)
    dest.write_text('/* Data Darbar - GDP deflator by fiscal year, for real/nominal views.\n'
                    '   Generated by etl/economy/build_deflator.py; do not edit by hand. */\n'
                    'window.DD_DEFLATOR=' + json.dumps(out, separators=(',', ':')) + ';\n')
    print(f'{dest}: GDP deflator {years[0]} to {years[-1]} (2015-16 = 100), '
          f'linked at {link} (factor {factor:.5f}); real series in {base} rupees')


if __name__ == '__main__':
    main()
