"""The headline macro series, and the quarterly national accounts.

Two warehouse tables that no page drew.

gdp_indicators is 27 years of the four numbers every other figure on the site
is implicitly deflated or divided by: output, net primary income from abroad,
real income per person, and the rupee. econ_data.js already carries an
`indicators` block of eleven such series and uses exactly two of them, invisibly,
to build a GDP deflator for the budget chart. Nothing was ever drawn from it.

gva_by_activity_quarterly is the same national accounts cut by quarter rather
than year: 10 fiscal years x 4 quarters x 22 activities, 2015-16 to 2024-25. It
is the only quarterly output series Pakistan publishes, and it is the only way
to see the lockdown quarter - industry falls a fifth between Jan-Mar and
Apr-Jun 2020 while agriculture does not move at all. An annual series cannot
show that; it averages it away.

The quarters are checked against the annual table rather than trusted: the four
quarters sum to the published annual GDP to the rupee for nine of the ten
years. The tenth, 2024-25, comes to 99.8 per cent because PBS revised the
annual figure after splitting the quarters, and the chart says so rather than
hiding a 72-billion-rupee discrepancy.

Usage: build_macro_payload.py --warehouse <dir> --out <js>
"""
import argparse, json, pathlib

import duckdb


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warehouse', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    con = duckdb.connect()
    con.execute('SET threads TO 1')
    W = pathlib.Path(a.warehouse).as_posix()
    rows = lambda sql: [list(r) for r in con.sql(sql).fetchall()]

    # Output, income and the rupee. GNI is GDP plus net primary income from
    # abroad, which is overwhelmingly remittances: it is negative until
    # 2001-02 and 3.2 trillion by 2023-24, so the gap between the two lines is
    # the diaspora's contribution to the national accounts.
    head = rows(f"""
        SELECT fy, fy_end,
               round(gdp_constant_pkr_mn / 1e6, 3)                      AS gdp_tn,
               round((gdp_constant_pkr_mn + COALESCE(npi_constant_pkr_mn, 0))
                     / 1e6, 3)                                          AS gni_tn,
               CASE WHEN npi_constant_pkr_mn IS NULL THEN NULL
                    ELSE round(npi_constant_pkr_mn / 1e6, 3) END        AS npi_tn,
               CASE WHEN per_capita_income_constant_rs IS NULL THEN NULL
                    ELSE round(per_capita_income_constant_rs) END       AS pci,
               round(exchange_rate_pkr_per_usd, 2)                      AS usd
        FROM '{W}/gdp_indicators.parquet'
        ORDER BY fy_end""")

    # Every activity, every quarter. 880 rows is small enough to ship whole and
    # aggregate in the browser, which keeps the sector / subsector / activity
    # views one dataset rather than three pre-baked ones that could disagree.
    qtr = rows(f"""
        SELECT fy, fy_end, quarter, sector, subsector, category,
               round(gva_constant_pkr_mn, 1)
        FROM '{W}/gva_by_activity_quarterly.parquet'
        WHERE gva_constant_pkr_mn IS NOT NULL
        ORDER BY fy_end, quarter, sector, subsector, category""")

    # Does the quarterly split add back up to the year? Reported, not assumed.
    recon = rows(f"""
        SELECT q.fy,
               round(sum(q.gva_constant_pkr_mn) / 1e6, 3)               AS qtr_tn,
               round(any_value(g.gdp_constant_pkr_mn) / 1e6, 3)         AS ann_tn,
               round(100.0 * sum(q.gva_constant_pkr_mn)
                     / any_value(g.gdp_constant_pkr_mn), 2)             AS pct
        FROM '{W}/gva_by_activity_quarterly.parquet' q
        JOIN '{W}/gdp_indicators.parquet' g USING (fy)
        GROUP BY 1 ORDER BY 1""")

    payload = {
        'headline': {'rows': head,
                     'cols': ['fy', 'fy_end', 'gdp_tn', 'gni_tn', 'npi_tn',
                              'pci', 'usd']},
        'quarterly': {'rows': qtr,
                      'cols': ['fy', 'fy_end', 'quarter', 'sector',
                               'subsector', 'category', 'gva_mn']},
        'qtr_check': {'rows': recon, 'cols': ['fy', 'qtr_tn', 'ann_tn', 'pct']},
    }
    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        '/* Data Darbar - headline macro series and quarterly national\n'
        '   accounts. Generated by etl/economy/build_macro_payload.py;\n'
        '   do not edit by hand. */\n'
        'window.DD_MACRO=' + json.dumps(payload, separators=(',', ':')) + ';\n')

    # The quarters must reconstruct the year, or the chart is drawing a
    # different economy from the one on the rest of the page.
    worst = min(r[3] for r in recon)
    assert worst > 99.5, f'quarters only reach {worst}% of an annual GDP'
    assert len({(r[0], r[2]) for r in qtr}) == len(recon) * 4, \
        'a fiscal year is missing a quarter'
    for k in payload:
        print(f'  {k:<10} {len(payload[k]["rows"]):>5,} rows')
    print(f'  per-person real income peaks at Rs '
          f'{max(r[5] for r in head if r[5]):,.0f}, latest Rs '
          f'{[r[5] for r in head if r[5]][-1]:,.0f}')
    print(f'  quarters reconcile to the year: {worst:.2f}% at worst')
    print(f'  -> {out} ({out.stat().st_size/1e3:.1f} KB)')


if __name__ == '__main__':
    main()
