"""The State explorer's payload: what the state collects, and what it does not.

Only one of State's five themes has data on the site today, and the page says
so rather than showing four empty tabs. What it has:

  Public money   FBR's collection by head, 1991-92 to 2023-24, which totals
                 9.3 trillion rupees in the last year - FBR's own figure.

The federal budget is in the warehouse as budget_lines and is not a series yet.
It is 18 years of budget documents whose item labels drift between them -
"EXPENDITURE (I + II)" one year, "Current Exp. on Revenue Receipts" another,
some carrying figures inside the label - so no item name spans more than five
of the eighteen years. Charting it needs an item crosswalk across the
documents, the same kind of work the census districts needed, and inventing one
here would produce a line that looks continuous and is not.

Justice, crime and policing have pipelines under etl/ that reach no published
table. Energy and weather disasters have no data at all.

Usage:
  build_state_payload.py --warehouse <dir> --out <js>
"""
import argparse, json, pathlib

import duckdb


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warehouse', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    con = duckdb.connect()
    con.execute('SET threads TO 1')
    W = pathlib.Path(a.warehouse)

    tax = con.sql(f"""
        SELECT fy, fy_end, tax_type, head,
               round(sum(collection_pkr_mn), 1) AS pkr_mn
        FROM '{(W / 'fbr_tax_collection.parquet').as_posix()}'
        WHERE collection_pkr_mn IS NOT NULL
        GROUP BY 1, 2, 3, 4
        ORDER BY fy_end, tax_type, head""").fetchall()

    budget = con.sql(f"""
        SELECT count(*) AS rows, count(DISTINCT doc_fy) AS docs,
               min(doc_fy) AS first_doc, max(doc_fy) AS last_doc,
               count(DISTINCT item) AS items
        FROM '{(W / 'budget_lines.parquet').as_posix()}'""").fetchone()

    payload = {
        'tax': {
            'rows': [[r[0], r[1], r[2], r[3], r[4]] for r in tax],
            'cols': ['fy', 'fy_end', 'tax_type', 'head', 'pkr_mn'],
        },
        'budget': {
            'rows': budget[0], 'docs': budget[1],
            'first': budget[2], 'last': budget[3], 'items': budget[4],
        },
    }
    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        '/* Data Darbar - State explorer payload. Generated by\n'
        '   etl/economy/build_state_payload.py; do not edit by hand. */\n'
        'window.DD_STATE=' + json.dumps(payload, separators=(',', ':')) + ';\n')
    print(f'  {len(tax):,} tax rows, {payload["budget"]["docs"]} budget documents'
          f'  -> {out} ({out.stat().st_size/1e3:.1f} KB)')
    print(con.sql(f"""SELECT fy, round(sum(collection_pkr_mn)/1e6, 2) AS pkr_tn
        FROM '{(W / 'fbr_tax_collection.parquet').as_posix()}'
        GROUP BY 1 ORDER BY 1 DESC LIMIT 3""").df().to_string(index=False))


if __name__ == '__main__':
    main()
