"""Emigration: where Pakistanis go, with what skills, into what work.

Three tables in the warehouse that no page drew. They are the other half of
the remittance story money.html already tells - the money comes back because
the people went - and the district-of-origin counts are already on the Places
map, so this is the destination end of the same series.

One thing the data does that would wreck a chart if taken at face value:
diaspora_destinations carries year = -1 for 197 rows. That is not a year, it
is the cumulative total since records began - 8,670,724 people, Saudi Arabia
4.4m, the UAE 2.8m - and adding it to the annual rows would roughly double
every country. It is kept, because it is the most useful single figure in the
table, but kept apart.

Usage: build_migration_payload.py --warehouse <dir> --out <js>
"""
import argparse, json, pathlib

import duckdb


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warehouse', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    con = duckdb.connect()
    con.execute('SET threads TO 1')
    W = pathlib.Path(a.warehouse).as_posix()
    rows = lambda sql: [list(r) for r in con.sql(sql).fetchall()]

    # The cumulative total per country, which is the year = -1 sentinel.
    total = rows(f"""
        SELECT country, continent, CAST(emigrants AS BIGINT)
        FROM '{W}/diaspora_destinations.parquet'
        WHERE year = -1 AND emigrants > 0
        ORDER BY emigrants DESC""")

    # And the annual rows, which are a different universe: 2011 onward only.
    annual = rows(f"""
        SELECT year, country, CAST(emigrants AS BIGINT)
        FROM '{W}/diaspora_destinations.parquet'
        WHERE year >= 1970 AND emigrants > 0
        ORDER BY year, emigrants DESC""")

    skill = rows(f"""
        SELECT year, mode, skill_level, CAST(emigrants AS BIGINT)
        FROM '{W}/diaspora_emigrants_by_skill.parquet'
        WHERE emigrants IS NOT NULL
        ORDER BY year, skill_level""")

    occ = rows(f"""
        SELECT occupation, CAST(emigrants AS BIGINT)
        FROM '{W}/diaspora_occupations.parquet'
        WHERE emigrants > 0
        ORDER BY emigrants DESC""")

    payload = {
        'total': {'rows': total, 'cols': ['country', 'continent', 'emigrants']},
        'annual': {'rows': annual, 'cols': ['year', 'country', 'emigrants']},
        'skill': {'rows': skill,
                  'cols': ['year', 'mode', 'skill_level', 'emigrants']},
        'occupation': {'rows': occ, 'cols': ['occupation', 'emigrants']},
    }
    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        '/* Data Darbar - emigration payload. Generated by\n'
        '   etl/economy/build_migration_payload.py; do not edit by hand. */\n'
        'window.DD_MIGRATION=' + json.dumps(payload, separators=(',', ':')) + ';\n')

    grand = sum(r[2] for r in total)
    assert grand > 5e6, f'cumulative total looks wrong: {grand}'
    assert not any(r[0] < 1970 for r in annual), 'a sentinel year reached the annual rows'
    for k in payload:
        print(f'  {k:<11} {len(payload[k]["rows"]):>5,} rows')
    print(f'  cumulative emigrants {grand:,} across {len(total)} countries')
    print(f'  -> {out} ({out.stat().st_size/1e3:.1f} KB)')


if __name__ == '__main__':
    main()
