#!/usr/bin/env python3
"""
Rebuild app/data/tehsils_geo.js (window.DD_GEO_T) on PBS's own Census-2023 tehsil polygons.

Input : raw_data/geospatial/boundaries/pbs-census2023-2026-09-27/pbs_tehsils_2023.geojson
Output: app/data/tehsils_geo.js           649 features (the DISPUTED TERRITORY polygon is dropped)
        etl/geography/pbs_tehsil_index.csv   one row per feature: dd_id, name, district, dk, prov, merged, dds_id

Feature properties (the app reads dd_id / prov through GEOGRAPHIES.tehsil; the rest are for payload builders):
  dd_id   PBS tehsil code (3-digit string) — replaces the geoBoundaries shapeID hash as the tehsil key
  name    PBS tehsil name as published
  dk      Data Darbar district key (the district polygon's key), via etl/build_dataset.apply_crosswalk
  prov    province label as the app spells it
  merged  1 for the seven ex-FATA districts (kept for the health-access payload's merged_district flag)
  dds_id  Census-2023 unit id (Stage-2 warehouse) where the tehsil is a census unit
Geometry simplified (tolerance 0.001°, topology preserved) and rounded to 3 dp — the fidelity the census layer
was built at (worst area change 1.6%, median nil); one file now serves both tehsil geographies.
"""
import json, re, sys
from pathlib import Path
import pandas as pd
from shapely.geometry import shape, mapping
from shapely import set_precision
from shapely.validation import make_valid

REPO = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('.')
SRC = Path(sys.argv[2]) if len(sys.argv) > 2 else REPO.parent / 'raw_data/geospatial/boundaries/pbs-census2023-2026-09-27/pbs_tehsils_2023.geojson'
sys.path.insert(0, str(REPO / 'etl'))
from build_dataset import apply_crosswalk  # noqa: E402

PROV = {'KHYBER PAKHTUNKHWA': 'Khyber Pakhtunkhwa', 'PUNJAB': 'Punjab', 'SINDH': 'Sindh', 'BALOCHISTAN': 'Balochistan',
        'ISLAMABAD CAPITAL TERRITORY': 'Islamabad Capital Territory', 'GILGIT-BALTISTAN': 'Gilgit-Baltistan',
        'AZAD JAMMU & KASHMIR': 'Azad Jammu & Kashmir'}
# GB/AJK districts that the app's district layer names differently
DK_ALIAS = {'astore': 'astor', 'diamer': 'diamir', 'ghanche': 'ghanchi', 'hunza': 'hunza nagar', 'nagar': 'hunza nagar',
            'kharmang': 'skardu', 'shigar': 'skardu', 'jhelum valley': 'hattian', 'sudhnoti': 'sudhnutti',
            'malakand': 'malakand'}
MERGED = {'bajaur agency', 'khyber agency', 'kurram agency', 'mohmand agency', 'orakzai agency', 'north waziristan agency', 'south waziristan agency'}

def norm(s): return re.sub(r'\s+', ' ', re.sub(r'[^a-z0-9]+', ' ', (s or '').lower())).strip()
def dkey(district):
    k = norm(re.sub(r'\b(DISTRICT|PROTECTED AREA)\b', '', district))
    k = DK_ALIAS.get(k, k)
    return apply_crosswalk(k)

fc = json.load(open(SRC))
dist_keys = set(json.load(open(REPO / 'app/data/districts.json')).keys())
feats, rows = [], []
for f in sorted(fc['features'], key=lambda f: f['properties']['tehsil_code']):
    p = f['properties']
    if p['tehsil_code'] == '000': continue
    dk = dkey(p['district'])
    if dk not in dist_keys: raise SystemExit(f'no district key for {p["district"]} -> {dk}')
    g = shape(f['geometry']).simplify(0.001, preserve_topology=True)
    g = set_precision(g, 1e-3, mode='pointwise')
    if not g.is_valid:
        try: g = make_valid(g, method='structure', keep_collapsed=False)
        except Exception: g = g.buffer(0)
        if g.geom_type == 'GeometryCollection':
            from shapely.ops import unary_union
            g = unary_union([x for x in g.geoms if x.geom_type in ('Polygon', 'MultiPolygon')])
    props = {'dd_id': p['tehsil_code'], 'name': p['tehsil'], 'dk': dk, 'prov': PROV[p['province']], 'merged': int(dk in MERGED)}
    if p.get('dds_id'): props['dds_id'] = p['dds_id']
    feats.append({'type': 'Feature', 'properties': props, 'geometry': mapping(g)})
    rows.append(dict(dd_id=p['tehsil_code'], name=p['tehsil'], district=p['district'], district_code=p['district_code'], dk=dk,
                     prov=props['prov'], merged=props['merged'], dds_id=p.get('dds_id') or '', unit_type=p.get('unit_type') or ''))
out = REPO / 'app/data/tehsils_geo.js'
out.write_text('/* Data Darbar - tehsil geometry: PBS Census-2023 tehsils (649), one polygon per census unit plus GB/AJK.\n   dd_id = PBS tehsil code (the tehsil groups), dds_id = census unit id (the census layer).\n   Generated by etl/geography/build_tehsils_geo_pbs.py; do not edit by hand. */\n'
               'window.DD_GEO_T=' + json.dumps({'type': 'FeatureCollection', 'features': feats}, separators=(',', ':')) + ';\n', encoding='utf-8')
idx = REPO / 'etl/geography/pbs_tehsil_index.csv'
pd.DataFrame(rows).to_csv(idx, index=False)
print(f'{out}: {len(feats)} features, {out.stat().st_size/1e3:.0f} KB; index {idx}')
