"""The federal budget, grouped, for the State explorer.

The grouped budget - eighteen documents, receipts and current expenditure,
each year's items folded into the functional groups a reader can compare
across years - lives inside app/assets/js/econ_data.js, a 2.9 MB file the
Economy page loads whole. State draws three charts from 45 KB of it, and
should not pay for the rest, so this script copies that block out into its
own payload.

Nothing is recomputed here. The group crosswalk (which item label belongs to
which group in which document) is the one the Economy build made, and it is
a reading of the documents rather than a fact about them: no raw item label
spans more than five of the eighteen years. When that crosswalk moves into
the warehouse build proper, this script goes with it.

Usage:
  extract_budget_payload.py --app app
"""
import argparse, json, pathlib


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--app', required=True)
    a = ap.parse_args()
    app = pathlib.Path(a.app)
    src = (app / 'assets/js/econ_data.js').read_text()
    econ = json.loads(src[src.index('{'):src.rindex('}') + 1])
    budget = econ['budget']
    years = sorted(set(budget['receipts']) | set(budget['expenditure']))
    for side in ('receipts', 'expenditure'):
        for y, groups in budget[side].items():
            for g in groups:
                assert g['children'], f'{side} {y} {g["label"]} has no items'
    out = app / 'data/budget_data.js'
    out.write_text(
        '/* Data Darbar - the federal budget, grouped, for the State explorer.\n'
        '   Generated by scripts/extract_budget_payload.py from the Economy\n'
        '   build\'s crosswalk; do not edit by hand. */\n'
        'window.DD_BUDGET=' + json.dumps(
            {'years': years, 'receipts': budget['receipts'],
             'expenditure': budget['expenditure']},
            separators=(',', ':')) + ';\n')
    print(f'  {len(years)} budget years {years[0]} to {years[-1]}'
          f' -> {out} ({out.stat().st_size/1e3:.1f} KB)')


if __name__ == '__main__':
    main()
