"""Re-inline districts.json into census_data.js, the file the pages actually read.

app.js prefers `window.DD_DATA` over fetching `districts.json`, because the
inlined form is what lets the site run from file://. `data/census_data.js`
defines that global. So editing districts.json alone changes nothing on the
site: the map keeps serving whatever census_data.js last held. build_dataset.py
writes both at the end of a full run and warns about the drift in a comment,
but a full run rebuilds every layer from microdata, which is far too heavy when
a single ETL has added a handful of fields.

This does only the inlining step, byte-for-byte as build_dataset.py does it, so
run it after any script that touches districts.json:

    python etl/census2023_schooling_by_sex.py --census "<dir>" --write
    python etl/inline_districts.py
    python etl/build_web_warehouse.py --src <desktop warehouse>

It refuses to write if the GeoJSON is missing rather than emit a census_data.js
without geometry, which would leave the map with no polygons at all.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

APP = Path(__file__).resolve().parent.parent / "app" / "data"
DISTRICTS = APP / "districts.json"
GEOJSON = APP / "pakistan_districts_province_boundries.geojson"
INLINE_OUT = APP / "census_data.js"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--districts", type=Path, default=DISTRICTS)
    ap.add_argument("--geojson", type=Path, default=GEOJSON)
    ap.add_argument("--out", type=Path, default=INLINE_OUT)
    args = ap.parse_args()

    if not args.geojson.exists():
        sys.exit(f"ERROR: {args.geojson.name} not found. Refusing to write a "
                 f"census_data.js with no geometry — the map would render "
                 f"blank. Nothing changed.")

    data = json.loads(args.districts.read_text())
    geo = json.loads(args.geojson.read_text())

    before = set()
    if args.out.exists():
        txt = args.out.read_text()
        i = txt.find("window.DD_DATA=")
        if i != -1:
            try:
                old = json.loads(txt[i + len("window.DD_DATA="):].rstrip().rstrip(";"))
                before = {f for rec in old.values() for f in rec}
            except json.JSONDecodeError:
                pass

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("/* Data Darbar district data — inlined for file:// "
                "(window.DD_GEO / window.DD_DATA).\n"
                f"   Generated by etl/build_dataset.py — do not hand-edit. "
                f"{len(data)} districts. */\n")
        f.write("window.DD_GEO=")
        json.dump(geo, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
        f.write("window.DD_DATA=")
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    after = {field for rec in data.values() for field in rec}
    added = sorted(after - before)
    print(f"inlined {len(data)} districts -> {args.out}")
    print(f"  {len(after)} distinct fields; {len(added)} new since the last inline")
    if added:
        head = ", ".join(added[:8])
        print(f"  new: {head}{' …' if len(added) > 8 else ''}")


if __name__ == "__main__":
    main()
